/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BotonesAcciones;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Tadeo Nuñez
 */
public class PanelAccion extends javax.swing.JPanel {

    /**
     * Creates new form PanelAccion
     */
    public PanelAccion() {
        initComponents();

    }

    public void iniEvent(TableActionEvent event, int row) {
        cmbEditar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
            }
        });
        cmbBorrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });

        cmbOcultar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onView(row);  // Changed from array access to method call
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbEditar = new BotonesAcciones.ActionButton();
        cmbBorrar = new BotonesAcciones.ActionButton();
        cmbOcultar = new BotonesAcciones.ActionButton();

        setLayout(new java.awt.GridLayout(1, 0));

        cmbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesAdmin/editar.png"))); // NOI18N
        cmbEditar.setPreferredSize(new java.awt.Dimension(50, 50));
        add(cmbEditar);

        cmbBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesAdmin/Borrar.png"))); // NOI18N
        cmbBorrar.setPreferredSize(new java.awt.Dimension(50, 50));
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });
        add(cmbBorrar);

        cmbOcultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesAdmin/Ojo.png"))); // NOI18N
        cmbOcultar.setPreferredSize(new java.awt.Dimension(50, 50));
        cmbOcultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOcultarActionPerformed(evt);
            }
        });
        add(cmbOcultar);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBorrarActionPerformed

    private void cmbOcultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOcultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOcultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BotonesAcciones.ActionButton cmbBorrar;
    private BotonesAcciones.ActionButton cmbEditar;
    private BotonesAcciones.ActionButton cmbOcultar;
    // End of variables declaration//GEN-END:variables
}
